### ISSUE TITLE
ImapClient这是一个扩展的库吗？

### ISSUE THREAD

**Issue by leoskey** [cuicheng11165/SMTPEmail#1]

**Comment by cuicheng11165** [comment]
是的一个基于SMTP 协议的第三方的类库，目前没找到微软有现成的api。

**Comment by leoskey** [comment]
微软有一个SmtpClient类，可以实现类似的功能。

**Comment by cuicheng11165** [comment]
如果只是要发送email的话 smtpclient类能做到。获取所有的email信息，不知道微软是否有api能做到？
